
name: Project Status Auto Report
description: Creates an issue automatically with 
branding:
  icon: 'calendar'
  color: 'purple'
inputs:
  github_token:
    description: github token
    required: true
  project_id:
    description: the project to generate the report for
    required: true
  repo_owner:
    description: the owner of the repo the project is in
    required: true
  repo_name:
    description: the name of the repo the project is in
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PROJECT_ID: ${{ inputs.project_id }}
    REPO_OWNER: ${{ inputs.repo_owner }}
    REPO_NAME: ${{ inputs.repo_name }}
