
name: Project Status Auto Report
description: Creates an issue automatically with 
branding:
  icon: 'calendar'
  color: 'purple'
inputs:
  github_token:
    description: github token
    required: true
  git_user_name:
    description: user name who git push bundle update commit
    required: true
  git_email:
    description: email of user who git push bundle update commit
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GIT_USER_NAME: ${{ inputs.git_user_name }}
    GIT_EMAIL: ${{ inputs.git_email }}
